service: serverless-potato-lab
frameworkVersion: "4"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 25 # optional, in seconds, default is 6
  iam:
    role:
      name: serverless-my-super-role
      statements:
        - Effect: Allow
          Resource: "*"
          Action:
            - s3:*
            - sqs:*
            - events:*
          # Resource:
          #   - Fn::GetAtt: [ jobScrapperAnalyzeQueue, Arn ]

functions:
  authApi:
    handler: ./src/index.authHandler
    events:
      - httpApi:
          path: /auth/{proxy+}
          method: "*"
  dashboardApi:
    handler: ./src/index.dashboardHandler
    events:
      - httpApi:
          path: /dashboard/{proxy+}
          method: "*"
  schedulerApi:
    handler: ./src/index.schedulerHandler
    events:
      - httpApi:
          path: /scheduler
          method: "*"
  scrapperApi:
    handler: ./src/index.scrapperHandler
    events:
      - httpApi:
          path: /scrapper/{proxy+}
          method: "*"
  jobApi:
    handler: ./src/index.jobHandler
    events:
      - httpApi:
          path: /job/{proxy+}
          method: "*"
  jobScrapperAnalyzeReceiver:
    handler: ./src/index.jobScrapperAnalyzeReceiver
    events:
      - sqs: arn:aws:sqs:ap-southeast-1:767397903484:jobScrapperAnalyzeQueue
      # - sqs:
      #     arn:
      #       Fn::GetAtt:
      #         - jobScrapperAnalyzeQueue
      #         - Arn
  jobScrapperProcessReceiver:
    handler: ./src/index.jobScrapperProcessReceiver
    events:
      - sqs: arn:aws:sqs:ap-southeast-1:767397903484:jobScrapperProcessQueue
      # - sqs:
      #     arn:
      #       Fn::GetAtt:
      #         - jobScrapperProcessQueue
      #         - Arn

# resources:
#   Resources:
#     jobScrapperAnalyzeQueue:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: jobScrapperAnalyzeQueue
#     jobScrapperProcessQueue:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: jobScrapperProcessQueue

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: "2025-01-15"
    endpoint: http://0.0.0.0:9324
    region: ap-southeast-1
    skipCacheInvalidation: false

plugins:
  - serverless-offline-sqs
  - serverless-offline
  - serverless-dotenv-plugin
