import "./global.css";
import type { Metadata } from "next";

import { cn } from "@potato-lab/lib/utils";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import { SidebarProvider } from "@potato-lab/ui";
import { UserLayout } from "../components/layout/user-layout";

export const metadata: Metadata = {
  title: "Welcome to potato-lab-web",
  description: "Generated by create-nx-workspace",
};

const iosevkaMono = localFont({
  src: [
    {
      path: "../fonts/Iosevka-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Iosevka-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/Iosevka-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Iosevka-MediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../fonts/Iosevka-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Iosevka-SemiBoldItalic.woff2",
      weight: "600",
      style: "italic",
    },
    {
      path: "../fonts/Iosevka-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Iosevka-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-iosevka-mono",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "font-mono antialiased transition-opacity duration-300",
          iosevkaMono.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <SidebarProvider
            style={
              {
                "--sidebar-width-icon": "6rem",
              } as React.CSSProperties
            }
          >
            <UserLayout>{children}</UserLayout>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
