import "./global.css";
import type { Metadata } from "next";
import { cn } from "@potato-lab/lib/utils";

import { iosevkaMono } from "../fonts/Iosevka";
import RootProviders from "./providers";
import GlobalDialog from "../components/dialog/GlobalDialog";

export const metadata: Metadata = {
  title: "Welcome to potato-lab-web",
  description: "Generated by create-nx-workspace"
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "font-mono antialiased transition-opacity duration-300",
          iosevkaMono.variable
        )}
      >
        <RootProviders>{children}</RootProviders>
        <GlobalDialog />
      </body>
    </html>
  );
}
